### ISSUE TITLE
Not responding sometimes

### ISSUE THREAD

**Issue by SAEEDStarv** [my-telegram-bots/hitokoto_bot#1]
Demo bot [@hitokoto_bot](https://t.me/hitokoto_bot) not responding to commands sometimes :

![cfw.png](https://user-images.githubusercontent.com/30508362/113297725-3ac9de00-9310-11eb-9fe9-9ed2ce380959.png)

i thought maybe that's from your worker so i run it on my worker but it's have the same problem.

**Comment by makeding** [comment]
Due to cloudflare CPU running time limit (10ms),
the bot can only do simple functions and the bot can't resend the message in case of a request error.
