### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by halloall** [my-telegram-bots/hitokoto_bot#2]
求助一下, 我想要在你的bot基础上开发一个入群验证的机器人, 但是现在我希望能在提交的参数上加一个parse_mode=HTML,我在网上找了许多,但基本是python和php的,我自己试着加了几个地方但都不工作,你能帮帮我嘛,谢谢了

**Comment by makeding** [comment]
https://github.com/my-telegram-bots/hitokoto_bot/blob/be89a377cd2e7ff8023e9a62179525890d5ddbee/hitokoto_bot.js#L53

例子
```
await tg(token,'sendmessage',{
  chat_id: chat_id,
  parse_mode: "HTML",
})

**Comment by halloall** [comment]
> 
> 
> https://github.com/my-telegram-bots/hitokoto_bot/blob/be89a377cd2e7ff8023e9a62179525890d5ddbee/hitokoto_bot.js#L53
> 
> 例子
> 
> ```
> await tg(token,'sendmessage',{
>   chat_id: chat_id,
>   parse_mode: "HTML",
> })
> ```

非常感谢
