### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by ghost** [my-telegram-bots/hitokoto_bot#3]
![2022-01-14 17 38 16@2x](https://user-images.githubusercontent.com/88776768/149493668-fe2e5d62-d37b-4dc2-a491-9a5796acde1e.png)

查询 getWebhookInfo 发现是 SSL 报错，难道 cloudflare 证书不认吗

**Comment by makeding** [comment]
部署 bot 的域名不能带 `-` / `_`
带了会导致 tg 不识别证书

**Comment by ghost** [comment]
可以了，十分感谢！
